# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install json5 bs4 requests
    - name: Test with pytest
      run: python fetch.py
      env:
          UID: ${{secrets.UID}}
          AUTH: ${{secrets.AUTH}}
    - name: Commit files
      run: |
        git config --local user.email "andyjjrt@gmail.com"
        git config --local user.name "andyjjrt"
        git commit -m "daily update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
